"""Static reference data.

Deliberately offline. Every figure here is a documented approximation, and each
tool says so in its own output rather than presenting a lookup as a live quote.
A tool that silently passes off stale reference data as current is worse than
one that admits its source, because the model downstream cannot tell the
difference and the user never sees the seam.

Structure:
- `DESTINATIONS`  — 40 cities with region, tags, budget fit, best months and a
  per-quarter climate row.
- `CLIMATE_BY_LATITUDE` — the fallback when a city is not in the table, keyed
  by latitude band, so an unknown city still gets a defensible answer.
- `CURRENCY_RATES` — approximate units per USD.
- `VISA_RULES` — passport x destination outcomes for common pairs, with a
  documented default.
- `COUNTRY_REGION` — used for the flight-distance ladder.
"""

from typing import Any

# ---------------------------------------------------------------------------
# Climate
# ---------------------------------------------------------------------------

#: (temp_c_low, temp_c_high, rain) per quarter: Q1 Jan-Mar, Q2 Apr-Jun,
#: Q3 Jul-Sep, Q4 Oct-Dec.
Quarter = tuple[int, int, str]

MONTH_TO_QUARTER = {
    "january": 0,
    "february": 0,
    "march": 0,
    "april": 1,
    "may": 1,
    "june": 1,
    "july": 2,
    "august": 2,
    "september": 2,
    "october": 3,
    "november": 3,
    "december": 3,
    "winter": 0,
    "spring": 1,
    "summer": 2,
    "autumn": 3,
    "fall": 3,
}

CLIMATE_BY_LATITUDE: dict[str, list[Quarter]] = {
    "tropical": [(24, 32, "wet"), (25, 33, "wet"), (25, 32, "very wet"), (24, 31, "moderate")],
    "subtropical": [
        (10, 19, "moderate"),
        (17, 27, "moderate"),
        (23, 33, "wet"),
        (13, 23, "moderate"),
    ],
    "temperate": [(1, 9, "moderate"), (10, 20, "moderate"), (17, 27, "low"), (5, 15, "wet")],
    "continental": [(-8, 2, "snow"), (7, 19, "moderate"), (16, 27, "low"), (0, 10, "wet")],
    "arid": [(8, 21, "very low"), (18, 33, "very low"), (25, 41, "none"), (12, 26, "low")],
    "polar": [(-18, -6, "snow"), (-4, 6, "snow"), (5, 15, "low"), (-9, 1, "snow")],
}


def _d(
    city: str,
    country: str,
    region: str,
    band: str,
    tags: list[str],
    budget: list[str],
    best: list[str],
    climate: list[Quarter],
) -> dict[str, Any]:
    return {
        "city": city,
        "country": country,
        "region": region,
        "latitude_band": band,
        "tags": tags,
        "budget_fit": budget,
        "best_months": best,
        "climate": climate,
    }


DESTINATIONS: list[dict[str, Any]] = [
    _d(
        "Kyoto",
        "Japan",
        "east-asia",
        "temperate",
        ["temples", "food", "culture", "nature"],
        ["mid-range", "luxury"],
        ["March", "April", "October", "November"],
        [(2, 10, "low"), (12, 24, "moderate"), (23, 33, "wet"), (8, 19, "low")],
    ),
    _d(
        "Tokyo",
        "Japan",
        "east-asia",
        "temperate",
        ["food", "nightlife", "culture", "shopping"],
        ["mid-range", "luxury"],
        ["March", "April", "October", "November"],
        [(3, 12, "low"), (14, 25, "moderate"), (23, 31, "wet"), (9, 20, "low")],
    ),
    _d(
        "Bangkok",
        "Thailand",
        "southeast-asia",
        "tropical",
        ["food", "temples", "nightlife", "shopping"],
        ["budget", "mid-range"],
        ["November", "December", "January", "February"],
        [(23, 33, "low"), (26, 35, "moderate"), (25, 33, "very wet"), (23, 32, "moderate")],
    ),
    _d(
        "Bali",
        "Indonesia",
        "southeast-asia",
        "tropical",
        ["beach", "nature", "wellness", "temples"],
        ["budget", "mid-range", "luxury"],
        ["May", "June", "July", "September"],
        [(24, 31, "very wet"), (24, 31, "low"), (23, 30, "low"), (24, 31, "wet")],
    ),
    _d(
        "Hanoi",
        "Vietnam",
        "southeast-asia",
        "subtropical",
        ["food", "culture", "history"],
        ["budget", "mid-range"],
        ["October", "November", "March", "April"],
        [(15, 22, "moderate"), (24, 32, "wet"), (26, 33, "very wet"), (19, 27, "moderate")],
    ),
    _d(
        "Singapore",
        "Singapore",
        "southeast-asia",
        "tropical",
        ["food", "shopping", "family", "museums"],
        ["mid-range", "luxury"],
        ["February", "March", "April"],
        [(24, 31, "moderate"), (25, 32, "moderate"), (25, 31, "moderate"), (24, 31, "wet")],
    ),
    _d(
        "Seoul",
        "South Korea",
        "east-asia",
        "continental",
        ["food", "shopping", "culture", "nightlife"],
        ["mid-range", "luxury"],
        ["April", "May", "September", "October"],
        [(-6, 4, "snow"), (10, 24, "moderate"), (22, 30, "very wet"), (3, 15, "low")],
    ),
    _d(
        "Jaipur",
        "India",
        "south-asia",
        "arid",
        ["history", "culture", "shopping"],
        ["budget", "mid-range"],
        ["November", "December", "January", "February"],
        [(9, 26, "very low"), (25, 40, "very low"), (26, 34, "wet"), (13, 29, "very low")],
    ),
    _d(
        "Goa",
        "India",
        "south-asia",
        "tropical",
        ["beach", "nightlife", "food", "wellness"],
        ["budget", "mid-range"],
        ["November", "December", "January", "February"],
        [(21, 32, "very low"), (26, 33, "wet"), (24, 29, "very wet"), (22, 33, "low")],
    ),
    _d(
        "Dubai",
        "United Arab Emirates",
        "middle-east",
        "arid",
        ["shopping", "luxury", "family", "beach"],
        ["mid-range", "luxury"],
        ["November", "December", "January", "February", "March"],
        [(15, 26, "very low"), (24, 39, "none"), (30, 41, "none"), (19, 32, "very low")],
    ),
    _d(
        "Istanbul",
        "Turkey",
        "middle-east",
        "temperate",
        ["history", "food", "culture", "shopping"],
        ["budget", "mid-range"],
        ["April", "May", "September", "October"],
        [(4, 11, "wet"), (12, 24, "moderate"), (20, 29, "low"), (9, 18, "wet")],
    ),
    _d(
        "Cairo",
        "Egypt",
        "africa",
        "arid",
        ["history", "museums", "culture"],
        ["budget", "mid-range"],
        ["October", "November", "March", "April"],
        [(9, 22, "very low"), (18, 35, "none"), (23, 35, "none"), (14, 28, "very low")],
    ),
    _d(
        "Marrakesh",
        "Morocco",
        "africa",
        "arid",
        ["culture", "shopping", "food", "history"],
        ["budget", "mid-range", "luxury"],
        ["March", "April", "October", "November"],
        [(7, 20, "low"), (14, 31, "very low"), (20, 37, "none"), (10, 24, "low")],
    ),
    _d(
        "Cape Town",
        "South Africa",
        "africa",
        "temperate",
        ["beach", "nature", "food", "wine"],
        ["mid-range", "luxury"],
        ["November", "December", "February", "March"],
        [(17, 26, "very low"), (11, 20, "wet"), (8, 18, "wet"), (14, 24, "low")],
    ),
    _d(
        "Nairobi",
        "Kenya",
        "africa",
        "subtropical",
        ["nature", "safari", "family"],
        ["mid-range", "luxury"],
        ["January", "February", "July", "August", "September"],
        [(13, 26, "moderate"), (14, 24, "very wet"), (12, 23, "low"), (14, 24, "wet")],
    ),
    _d(
        "Paris",
        "France",
        "temperate",
        "temperate",
        ["museums", "food", "culture", "shopping"],
        ["mid-range", "luxury"],
        ["May", "June", "September", "October"],
        [(3, 10, "moderate"), (10, 21, "moderate"), (15, 25, "low"), (6, 13, "wet")],
    ),
    _d(
        "Rome",
        "Italy",
        "europe",
        "subtropical",
        ["history", "food", "museums", "culture"],
        ["mid-range", "luxury"],
        ["April", "May", "September", "October"],
        [(4, 14, "moderate"), (12, 26, "low"), (19, 31, "very low"), (9, 20, "wet")],
    ),
    _d(
        "Barcelona",
        "Spain",
        "europe",
        "subtropical",
        ["beach", "food", "nightlife", "museums"],
        ["mid-range", "luxury"],
        ["May", "June", "September"],
        [(7, 15, "low"), (14, 24, "low"), (20, 29, "very low"), (11, 20, "moderate")],
    ),
    _d(
        "Lisbon",
        "Portugal",
        "europe",
        "subtropical",
        ["food", "beach", "culture", "nightlife"],
        ["budget", "mid-range"],
        ["April", "May", "September", "October"],
        [(9, 17, "wet"), (14, 25, "low"), (18, 28, "very low"), (12, 20, "wet")],
    ),
    _d(
        "Amsterdam",
        "Netherlands",
        "europe",
        "temperate",
        ["museums", "nightlife", "culture", "cycling"],
        ["mid-range", "luxury"],
        ["April", "May", "September"],
        [(1, 8, "wet"), (8, 19, "moderate"), (13, 22, "moderate"), (4, 12, "wet")],
    ),
    _d(
        "Prague",
        "Czechia",
        "europe",
        "continental",
        ["history", "nightlife", "architecture", "beer"],
        ["budget", "mid-range"],
        ["May", "June", "September"],
        [(-3, 5, "snow"), (8, 21, "moderate"), (13, 24, "moderate"), (2, 10, "wet")],
    ),
    _d(
        "Reykjavik",
        "Iceland",
        "europe",
        "polar",
        ["nature", "adventure", "northern-lights"],
        ["mid-range", "luxury"],
        ["June", "July", "August", "September"],
        [(-2, 3, "snow"), (4, 12, "moderate"), (9, 15, "moderate"), (0, 6, "wet")],
    ),
    _d(
        "Edinburgh",
        "United Kingdom",
        "europe",
        "temperate",
        ["history", "festivals", "nature", "whisky"],
        ["mid-range", "luxury"],
        ["May", "June", "August", "September"],
        [(1, 8, "wet"), (7, 17, "moderate"), (11, 19, "moderate"), (3, 11, "wet")],
    ),
    _d(
        "London",
        "United Kingdom",
        "europe",
        "temperate",
        ["museums", "history", "theatre", "shopping"],
        ["mid-range", "luxury"],
        ["May", "June", "September"],
        [(3, 10, "wet"), (9, 20, "moderate"), (14, 23, "moderate"), (6, 13, "wet")],
    ),
    _d(
        "Vienna",
        "Austria",
        "europe",
        "continental",
        ["music", "museums", "history", "food"],
        ["mid-range", "luxury"],
        ["April", "May", "September", "October"],
        [(-2, 6, "snow"), (9, 22, "moderate"), (15, 26, "moderate"), (2, 11, "wet")],
    ),
    _d(
        "Athens",
        "Greece",
        "europe",
        "subtropical",
        ["history", "beach", "food", "nightlife"],
        ["budget", "mid-range"],
        ["April", "May", "September", "October"],
        [(6, 15, "moderate"), (14, 28, "low"), (22, 34, "none"), (11, 22, "wet")],
    ),
    _d(
        "Santorini",
        "Greece",
        "europe",
        "subtropical",
        ["beach", "romance", "wine", "views"],
        ["mid-range", "luxury"],
        ["May", "June", "September", "October"],
        [(10, 15, "wet"), (16, 25, "low"), (22, 29, "none"), (14, 21, "wet")],
    ),
    _d(
        "Zurich",
        "Switzerland",
        "europe",
        "continental",
        ["nature", "mountains", "museums", "luxury"],
        ["luxury"],
        ["June", "July", "August", "September"],
        [(-2, 6, "snow"), (8, 21, "moderate"), (14, 25, "moderate"), (2, 11, "wet")],
    ),
    _d(
        "New York",
        "United States",
        "north-america",
        "temperate",
        ["museums", "food", "shopping", "nightlife"],
        ["mid-range", "luxury"],
        ["May", "June", "September", "October"],
        [(-2, 8, "snow"), (12, 25, "moderate"), (20, 29, "moderate"), (5, 15, "moderate")],
    ),
    _d(
        "San Francisco",
        "United States",
        "north-america",
        "temperate",
        ["food", "nature", "tech", "museums"],
        ["mid-range", "luxury"],
        ["September", "October"],
        [(8, 15, "wet"), (11, 19, "very low"), (12, 21, "none"), (9, 17, "wet")],
    ),
    _d(
        "New Orleans",
        "United States",
        "north-america",
        "subtropical",
        ["food", "music", "nightlife", "history"],
        ["budget", "mid-range"],
        ["February", "March", "April", "November"],
        [(7, 19, "moderate"), (18, 30, "wet"), (24, 33, "very wet"), (11, 23, "moderate")],
    ),
    _d(
        "Vancouver",
        "Canada",
        "north-america",
        "temperate",
        ["nature", "food", "mountains", "family"],
        ["mid-range", "luxury"],
        ["June", "July", "August", "September"],
        [(2, 9, "wet"), (10, 20, "moderate"), (14, 23, "low"), (4, 12, "wet")],
    ),
    _d(
        "Mexico City",
        "Mexico",
        "north-america",
        "subtropical",
        ["food", "museums", "history", "culture"],
        ["budget", "mid-range"],
        ["March", "April", "October", "November"],
        [(7, 24, "very low"), (13, 27, "wet"), (13, 24, "very wet"), (9, 23, "low")],
    ),
    _d(
        "Cancun",
        "Mexico",
        "north-america",
        "tropical",
        ["beach", "nightlife", "family", "diving"],
        ["budget", "mid-range", "luxury"],
        ["December", "January", "February", "March"],
        [(20, 29, "low"), (24, 33, "moderate"), (25, 33, "very wet"), (22, 30, "wet")],
    ),
    _d(
        "Havana",
        "Cuba",
        "central-america",
        "tropical",
        ["music", "history", "beach", "culture"],
        ["budget", "mid-range"],
        ["December", "January", "February", "March"],
        [(18, 27, "low"), (22, 31, "wet"), (24, 32, "very wet"), (20, 29, "moderate")],
    ),
    _d(
        "Rio de Janeiro",
        "Brazil",
        "south-america",
        "tropical",
        ["beach", "nightlife", "nature", "music"],
        ["budget", "mid-range", "luxury"],
        ["May", "June", "September", "October"],
        [(23, 31, "wet"), (19, 27, "moderate"), (18, 26, "low"), (21, 29, "moderate")],
    ),
    _d(
        "Buenos Aires",
        "Argentina",
        "south-america",
        "subtropical",
        ["food", "tango", "culture", "nightlife"],
        ["budget", "mid-range"],
        ["March", "April", "October", "November"],
        [(20, 30, "moderate"), (11, 20, "moderate"), (8, 17, "low"), (16, 26, "moderate")],
    ),
    _d(
        "Cusco",
        "Peru",
        "south-america",
        "temperate",
        ["history", "hiking", "nature", "culture"],
        ["budget", "mid-range"],
        ["May", "June", "July", "August", "September"],
        [(6, 19, "very wet"), (4, 20, "low"), (2, 20, "very low"), (6, 20, "moderate")],
    ),
    _d(
        "Sydney",
        "Australia",
        "oceania",
        "subtropical",
        ["beach", "food", "nature", "family"],
        ["mid-range", "luxury"],
        ["October", "November", "March", "April"],
        [(19, 26, "moderate"), (12, 21, "moderate"), (9, 18, "moderate"), (15, 23, "moderate")],
    ),
    _d(
        "Queenstown",
        "New Zealand",
        "oceania",
        "temperate",
        ["adventure", "nature", "mountains", "wine"],
        ["mid-range", "luxury"],
        ["December", "January", "February", "March"],
        [(10, 22, "low"), (4, 15, "moderate"), (0, 9, "snow"), (6, 17, "moderate")],
    ),
]

DESTINATION_BY_CITY = {d["city"].lower(): d for d in DESTINATIONS}

# ---------------------------------------------------------------------------
# Currency — approximate units per 1 USD, reference values only.
# ---------------------------------------------------------------------------

CURRENCY_RATES: dict[str, float] = {
    "USD": 1.0,
    "EUR": 0.92,
    "GBP": 0.79,
    "JPY": 152.0,
    "CNY": 7.24,
    "INR": 83.4,
    "AUD": 1.52,
    "CAD": 1.36,
    "CHF": 0.89,
    "SGD": 1.35,
    "THB": 36.2,
    "IDR": 15800.0,
    "VND": 24600.0,
    "KRW": 1345.0,
    "MXN": 17.1,
    "BRL": 5.05,
    "ZAR": 18.7,
    "AED": 3.67,
    "TRY": 32.2,
    "EGP": 47.5,
    "MAD": 10.0,
    "NZD": 1.66,
    "ARS": 880.0,
    "PEN": 3.72,
    "CZK": 23.2,
    "ISK": 138.0,
    "CUP": 24.0,
    "KES": 131.0,
}

COUNTRY_CURRENCY: dict[str, str] = {
    "japan": "JPY",
    "thailand": "THB",
    "indonesia": "IDR",
    "vietnam": "VND",
    "singapore": "SGD",
    "south korea": "KRW",
    "india": "INR",
    "united arab emirates": "AED",
    "turkey": "TRY",
    "egypt": "EGP",
    "morocco": "MAD",
    "south africa": "ZAR",
    "kenya": "KES",
    "france": "EUR",
    "italy": "EUR",
    "spain": "EUR",
    "portugal": "EUR",
    "netherlands": "EUR",
    "czechia": "CZK",
    "iceland": "ISK",
    "united kingdom": "GBP",
    "austria": "EUR",
    "greece": "EUR",
    "switzerland": "CHF",
    "united states": "USD",
    "canada": "CAD",
    "mexico": "MXN",
    "cuba": "CUP",
    "brazil": "BRL",
    "argentina": "ARS",
    "peru": "PEN",
    "australia": "AUD",
    "new zealand": "NZD",
}

# ---------------------------------------------------------------------------
# Visas
# ---------------------------------------------------------------------------

VISA_FREE = "visa-free"
VISA_ON_ARRIVAL = "visa on arrival"
E_VISA = "e-visa required"
VISA_REQUIRED = "visa required in advance"
ETA = "electronic travel authorisation required"

#: passport country -> destination country -> (outcome, max stay days or None)
VISA_RULES: dict[str, dict[str, tuple[str, int | None]]] = {
    "united states": {
        "japan": (VISA_FREE, 90),
        "france": (VISA_FREE, 90),
        "italy": (VISA_FREE, 90),
        "spain": (VISA_FREE, 90),
        "portugal": (VISA_FREE, 90),
        "greece": (VISA_FREE, 90),
        "united kingdom": (VISA_FREE, 180),
        "thailand": (VISA_FREE, 60),
        "singapore": (VISA_FREE, 90),
        "south korea": (ETA, 90),
        "india": (E_VISA, 30),
        "vietnam": (E_VISA, 90),
        "indonesia": (VISA_ON_ARRIVAL, 30),
        "turkey": (VISA_FREE, 90),
        "egypt": (VISA_ON_ARRIVAL, 30),
        "morocco": (VISA_FREE, 90),
        "south africa": (VISA_FREE, 90),
        "kenya": (E_VISA, 90),
        "united arab emirates": (VISA_ON_ARRIVAL, 30),
        "brazil": (VISA_FREE, 90),
        "argentina": (VISA_FREE, 90),
        "peru": (VISA_FREE, 183),
        "mexico": (VISA_FREE, 180),
        "canada": (VISA_FREE, 180),
        "cuba": (VISA_REQUIRED, 30),
        "australia": (ETA, 90),
        "new zealand": (ETA, 90),
        "iceland": (VISA_FREE, 90),
        "czechia": (VISA_FREE, 90),
        "netherlands": (VISA_FREE, 90),
        "austria": (VISA_FREE, 90),
        "switzerland": (VISA_FREE, 90),
        "china": (VISA_REQUIRED, 30),
    },
    "india": {
        "japan": (VISA_REQUIRED, 90),
        "thailand": (VISA_ON_ARRIVAL, 15),
        "singapore": (VISA_REQUIRED, 30),
        "indonesia": (VISA_ON_ARRIVAL, 30),
        "vietnam": (E_VISA, 90),
        "united arab emirates": (VISA_ON_ARRIVAL, 14),
        "united kingdom": (VISA_REQUIRED, 180),
        "france": (VISA_REQUIRED, 90),
        "united states": (VISA_REQUIRED, 180),
        "turkey": (E_VISA, 30),
        "egypt": (VISA_REQUIRED, 30),
        "morocco": (VISA_FREE, 90),
        "south africa": (VISA_REQUIRED, 90),
        "kenya": (E_VISA, 90),
        "mexico": (VISA_REQUIRED, 180),
        "brazil": (E_VISA, 90),
        "australia": (VISA_REQUIRED, 90),
        "new zealand": (VISA_REQUIRED, 90),
    },
    "united kingdom": {
        "japan": (VISA_FREE, 90),
        "united states": (ETA, 90),
        "thailand": (VISA_FREE, 60),
        "india": (E_VISA, 30),
        "france": (VISA_FREE, 90),
        "italy": (VISA_FREE, 90),
        "spain": (VISA_FREE, 90),
        "australia": (ETA, 90),
        "canada": (ETA, 180),
        "singapore": (VISA_FREE, 90),
        "turkey": (VISA_FREE, 90),
    },
    "germany": {
        "japan": (VISA_FREE, 90),
        "united states": (ETA, 90),
        "thailand": (VISA_FREE, 60),
        "india": (E_VISA, 30),
        "united kingdom": (VISA_FREE, 180),
        "australia": (ETA, 90),
    },
    "australia": {
        "japan": (VISA_FREE, 90),
        "united states": (ETA, 90),
        "thailand": (VISA_FREE, 60),
        "india": (E_VISA, 30),
        "united kingdom": (VISA_FREE, 180),
        "new zealand": (VISA_FREE, 90),
    },
    "canada": {
        "japan": (VISA_FREE, 90),
        "united states": (VISA_FREE, 180),
        "thailand": (VISA_FREE, 60),
        "india": (E_VISA, 30),
        "united kingdom": (VISA_FREE, 180),
        "france": (VISA_FREE, 90),
    },
    "japan": {
        "united states": (ETA, 90),
        "thailand": (VISA_FREE, 30),
        "france": (VISA_FREE, 90),
        "india": (E_VISA, 30),
        "united kingdom": (VISA_FREE, 180),
        "singapore": (VISA_FREE, 30),
    },
    "china": {
        "japan": (VISA_REQUIRED, 90),
        "thailand": (VISA_FREE, 30),
        "singapore": (VISA_FREE, 30),
        "united states": (VISA_REQUIRED, 90),
        "united kingdom": (VISA_REQUIRED, 180),
    },
    "brazil": {
        "japan": (VISA_FREE, 90),
        "france": (VISA_FREE, 90),
        "united states": (VISA_REQUIRED, 90),
        "argentina": (VISA_FREE, 90),
        "peru": (VISA_FREE, 183),
    },
    "south africa": {
        "united kingdom": (VISA_REQUIRED, 180),
        "united states": (VISA_REQUIRED, 90),
        "kenya": (VISA_FREE, 90),
        "thailand": (VISA_FREE, 30),
    },
}

#: Applied when the pair is not in the table. Stated explicitly in the output.
VISA_DEFAULT = (VISA_REQUIRED, None)

DISCLAIMER = (
    "Approximate reference data, not a live source. Verify against the destination's "
    "official immigration or consular website before booking."
)

# ---------------------------------------------------------------------------
# Regions — used for the flight-distance ladder.
# ---------------------------------------------------------------------------

COUNTRY_REGION: dict[str, str] = {
    "japan": "east-asia",
    "south korea": "east-asia",
    "china": "east-asia",
    "thailand": "southeast-asia",
    "vietnam": "southeast-asia",
    "indonesia": "southeast-asia",
    "singapore": "southeast-asia",
    "malaysia": "southeast-asia",
    "philippines": "southeast-asia",
    "india": "south-asia",
    "sri lanka": "south-asia",
    "nepal": "south-asia",
    "united arab emirates": "middle-east",
    "turkey": "middle-east",
    "israel": "middle-east",
    "qatar": "middle-east",
    "saudi arabia": "middle-east",
    "egypt": "africa",
    "morocco": "africa",
    "south africa": "africa",
    "kenya": "africa",
    "tanzania": "africa",
    "nigeria": "africa",
    "france": "europe",
    "italy": "europe",
    "spain": "europe",
    "portugal": "europe",
    "netherlands": "europe",
    "germany": "europe",
    "czechia": "europe",
    "austria": "europe",
    "greece": "europe",
    "switzerland": "europe",
    "iceland": "europe",
    "united kingdom": "europe",
    "ireland": "europe",
    "poland": "europe",
    "norway": "europe",
    "united states": "north-america",
    "canada": "north-america",
    "mexico": "north-america",
    "cuba": "central-america",
    "costa rica": "central-america",
    "panama": "central-america",
    "brazil": "south-america",
    "argentina": "south-america",
    "peru": "south-america",
    "chile": "south-america",
    "colombia": "south-america",
    "australia": "oceania",
    "new zealand": "oceania",
    "fiji": "oceania",
}

#: Regions that neighbour each other, for the "nearby region" flight band.
ADJACENT_REGIONS: dict[str, set[str]] = {
    "east-asia": {"southeast-asia", "south-asia"},
    "southeast-asia": {"east-asia", "south-asia", "oceania"},
    "south-asia": {"southeast-asia", "east-asia", "middle-east"},
    "middle-east": {"europe", "africa", "south-asia"},
    "africa": {"europe", "middle-east"},
    "europe": {"middle-east", "africa"},
    "north-america": {"central-america"},
    "central-america": {"north-america", "south-america"},
    "south-america": {"central-america"},
    "oceania": {"southeast-asia"},
}

#: band -> (economy low, economy high) round trip USD.
FLIGHT_BANDS: dict[str, tuple[int, int]] = {
    "same-city": (0, 0),
    "domestic": (120, 380),
    "same-region": (180, 550),
    "nearby-region": (400, 950),
    "intercontinental": (750, 1900),
}

CABIN_MULTIPLIERS: dict[str, float] = {
    "economy": 1.0,
    "premium": 1.9,
    "business": 3.6,
    "first": 6.0,
}
