"""Guards on what may enter the repository.

These are not tests of the product. They are tests of the repository itself,
and they exist because every one of the things they check has already gone
wrong once: a tooling directory reached a commit, a credential-bearing file was
one careless `git add` away from doing the same, and Next 16 quietly wrote an
editor instruction file into the tree on every `npm run dev`.

A convention in a README does not survive a hurried commit. A failing test does.

**These check shape, not names.** An earlier version of this file listed the
tools it knew about, which meant it passed for every tool that shipped after it
was written. The rules here are instead invariants about what belongs at the
root of this repository — one README, one CI directory, nothing else of either
kind — and those stay true no matter what generates the next stray file.

They also assert through `git check-ignore` rather than by searching
`.gitignore` for a substring, so what is tested is the rule's *effect*. A later
negation line that accidentally re-included something would pass a text search
and fail this.
"""

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

#: The only directory beginning with a dot that belongs in version control.
#: Everything else shaped like that is a tool's local workspace state.
ALLOWED_DOT_DIRS = {".github"}

#: The only markdown file that belongs at the repository root. Documentation
#: lives in docs/; anything else here was generated by something.
ALLOWED_ROOT_MARKDOWN = {"README.md"}


def _tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True)
    return out.stdout.splitlines()


def _is_ignored(path: str) -> bool:
    """Whether git would ignore `path`, asked of git rather than inferred.

    `--no-index` so the answer is about the rules, not about whether the file
    happens to exist or be tracked right now.
    """
    result = subprocess.run(
        ["git", "check-ignore", "--no-index", "-q", "--", path],
        cwd=ROOT,
        capture_output=True,
    )
    return result.returncode == 0


def test_no_tooling_directories_are_tracked():
    """No root-level dot-directory but the CI one may be tracked."""
    offenders = sorted(
        {
            f.split("/", 1)[0]
            for f in _tracked()
            if f.startswith(".") and "/" in f and f.split("/", 1)[0] not in ALLOWED_DOT_DIRS
        }
    )
    assert not offenders, f"tooling directories are tracked: {offenders}"


def test_tooling_directories_are_ignored():
    """Ignored, not merely absent — otherwise the next run of the tool re-adds them.

    Asked of a directory name that does not exist and never will, because the
    point is that the rule covers whatever appears, not the names known today.
    """
    assert _is_ignored(".some-editor-that-does-not-exist-yet/config.json")
    assert not _is_ignored(".github/workflows/ci.yml"), "CI must stay tracked"


def test_no_env_file_is_tracked():
    tracked = _tracked()
    assert ".env" not in tracked
    assert not [f for f in tracked if f.endswith("/.env")]


def test_env_example_carries_no_real_secrets():
    """Placeholders only. The example file is committed; the real one is not."""
    text = (ROOT / ".env.example").read_text()
    for marker in ("AKIA", "tvly-dev-", "sk-", "gsk_"):
        assert marker not in text, f"{marker!r} appears in .env.example"


def test_only_the_readme_is_tracked_at_the_root():
    """Frameworks and editors generate instruction files into the project root.

    Next 16 writes one on every `npm run dev` unless `agentRules` is off. This
    catches the day someone drops that setting, and equally the day some other
    tool starts doing the same thing under a name nobody has seen yet.
    """
    offenders = [
        f
        for f in _tracked()
        if "/" not in f and f.endswith(".md") and f not in ALLOWED_ROOT_MARKDOWN
    ]
    assert not offenders, f"unexpected markdown at the repository root: {offenders}"


def test_next_does_not_generate_instruction_files():
    config = (ROOT / "frontend" / "next.config.ts").read_text()
    assert "agentRules: false" in config, (
        "Next will write instruction files into the root without this"
    )


def test_generated_root_markdown_is_ignored():
    """The second line of defence, asked of git directly."""
    assert _is_ignored("SOME-GENERATED-FILE.md")
    assert not _is_ignored("README.md"), "the README must stay tracked"
    assert not _is_ignored("docs/VERSIONS.md"), "documentation must stay tracked"


def test_no_run_artifacts_are_tracked():
    """Screenshots of live browsing sessions are not source.

    v5 writes a JPEG per browser action into `data/runs/<thread>/`, and
    `storage._purge_artifacts` deletes the directory when the trip completes —
    transient by design. 157 of them reached this repository anyway, over ten
    commits, before anything checked. They are frames of real sessions on real
    commercial sites, which is the second reason not to publish them.
    """
    offenders = [f for f in _tracked() if f.startswith("data/runs/")]
    assert not offenders, f"{len(offenders)} run artifacts are tracked, e.g. {offenders[:3]}"
    assert _is_ignored("data/runs/some-thread-id/0001.jpg")


def test_the_systemd_units_point_at_scripts_that_exist():
    """A unit naming a script that was renamed fails at `systemctl start`, on
    someone else's server, with a message about an exit code."""
    import re

    units = sorted((ROOT / "deploy" / "systemd").glob("*.service"))
    assert units, "the deployment units are part of the deliverable"
    for unit in units:
        for path in re.findall(r"/opt/travel-planner/(\S+\.sh)", unit.read_text()):
            assert (ROOT / path).is_file(), f"{unit.name} runs {path}, which does not exist"


def test_every_script_is_executable():
    for script in sorted((ROOT / "scripts").glob("*.sh")):
        assert script.stat().st_mode & 0o111, f"{script.name} is not executable"
